export const GET_DIEASES_START = 'GET_DIEASES_START'

export const GET_DIEASES_END = 'GET_DIEASES_END'

export const GET_APPLIED_DISEASES = 'GET_APPLIED_DISEASES'

export const DEL_SELECTED_DISEASE = 'DEL_SELECTED_DISEASE'
